version: '3.7'
services:
  api:
    build:
      context: api
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
    expose:
      - 8000
    restart: unless-stopped
  postgres:
    image: postgres:11.5-alpine
    environment:
      - POSTGRES_DB=colorwheel
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
    expose:
      - 5432
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
