export default function appTypes() {
  return {
    AUTHENTICATE_USER: 'AUTHENTICATE_USER',
    AUTHENTICATE_NEW_USER: 'AUTHENTICATE_NEW_USER',
    SET_IS_USER_AUTHENTICATED: 'SET_IS_USER_AUTHENTICATED',
  };
}
