export default function appTypes() {
  return {
    AUTHENTICATE_SESSION: 'AUTHENTICATE_SESSION',
    AUTHENTICATE_USER: 'AUTHENTICATE_USER',
    DEAUTHENTICATE_USER: 'DEAUTHENTICATE_USER',
    SET_ACCESS_TOKEN: 'SET_ACCESS_TOKEN',
    SET_AUTHENTICATION_ERROR_MESSAGE: 'SET_AUTHENTICATION_ERROR_MESSAGE',
  };
}
