export default function userTypes() {
  return {
    AUTHENTICATE_SESSION: 'AUTHENTICATE_SESSION',
    AUTHENTICATE_USER: 'AUTHENTICATE_USER',
    DEAUTHENTICATE_USER: 'DEAUTHENTICATE_USER',
    HANDLE_AUTH_RESULTS: 'HANDLE_AUTH_RESULTS',
    SET_AUTHENTICATION_ERROR_MESSAGE: 'SET_AUTHENTICATION_ERROR_MESSAGE',
    SET_AUTO_LOGOUT_SCHEDULER: 'SET_AUTO_LOGOUT_SCHEDULER',
    SET_IS_AUTHENTICATING_USER: 'SET_IS_AUTHENTICATING_USER',
    SET_IS_LOGOUT_WARNING_MODAL_SHOWING: 'SET_IS_LOGOUT_WARNING_MODAL_SHOWING',
  };
}
