export default function userTypes() {
  return {
    AUTHENTICATE_SESSION: 'AUTHENTICATE_SESSION',
    AUTHENTICATE_USER: 'AUTHENTICATE_USER',
    DEAUTHENTICATE_USER: 'DEAUTHENTICATE_USER',
    HANDLE_AUTH_RESULTS: 'HANDLE_AUTH_RESULTS',
  };
}
