export default function userTypes() {
  return {
    AUTHENTICATE_SESSION: 'AUTHENTICATE_SESSION',
    AUTHENTICATE_USER: 'AUTHENTICATE_USER',
    DEAUTHENTICATE_USER: 'DEAUTHENTICATE_USER',
    SET_ACCESS_TOKEN: 'SET_ACCESS_TOKEN',
    SET_USER_EMAIL: 'SET_USER_EMAIL',
    SET_USER_ID: 'SET_USER_ID',
    SET_USER_NAME: 'SET_USER_NAME',
  };
}
