export default function userTypes() {
  return {
    AUTHENTICATE_SESSION: 'AUTHENTICATE_SESSION',
    AUTHENTICATE_USER: 'AUTHENTICATE_USER',
    DEAUTHENTICATE_USER: 'DEAUTHENTICATE_USER',
    SET_IS_LOGOUT_WARNING_MODAL_SHOWING: 'SET_IS_LOGOUT_WARNING_MODAL_SHOWING',
  };
}
